### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by Endrhythm** [osmose-model/osmose#9]
Hi Nicolas,
    Greetings!
    In OSMOSE 4.3.3, an error occurs below. I have carefully checked the dimensions and values of all my NetCDF files and CSV map files. I can't fix it. I know little about Java. What do you think is the most probable reason causing this issue?

![image](https://github.com/osmose-model/osmose/assets/34851469/6040781f-a78c-4cec-9f92-e350686c0966)

**Comment by barriern** [comment]
Hi @Boylad 

This error is due to the fact that for some reasons, the school cannot move because it on land and is surrounded by land. Therefore, there is no accessible surrounding cells and therefore the neighbour cell array has a length of 0, hence the error.

In order to be able to understand what the error might be, could you please send me your entire Osmose configuration (via FileSender or anything similar)?

Thanks

@barriern

**Comment by Endrhythm** [comment]
> Hi @Boylad
> 
> This error is due to the fact that for some reasons, the school cannot move because it on land and is surrounded by land. Therefore, there is no accessible surrounding cells and therefore the neighbour cell array has a length of 0, hence the error.
> 
> In order to be able to understand what the error might be, could you please send me your entire Osmose configuration (via FileSender or anything similar)?
> 
> Thanks
> 
> @barriern



> 

Yes! After increased the value of the `movement.randomwalk.range` , the code worked. I will continue to explore this model and will consult you again if I encounter any issues later on.
